### ISSUE TITLE
Could you please provide the version of each dependecies？

### ISSUE THREAD

**Issue by Gatsby23** [DeliriumV01D/NeRFpp#1]
Nice work！ But, there are something wrong on my labtop. I believe it may caused by the version of libtorch, could you please give a detailed version of each libraries？

**Comment by DeliriumV01D** [comment]
Thanks. I am using Windows OS. Library versions are as follows:
opencv-4.6.0
libtorch-win-shared-with-deps-2.0.1+cu118
cuda_11.8.0_522.06_windows
cudnn-windows-x86_64-8.9.2.26_cuda11

**Comment by Gatsby23** [comment]
Thank you very much, I'll try it again.
